from langchain_classic.chains.summarize import load_summarize_chain
from langchain_core.prompts import ChatPromptTemplate
from utils.document_processor import load_and_split
from config.llm import llm


def transcript_summarizer(file):
  final_text_docs = load_and_split(file)

  map_prompt = """
    Please make a concise and accurate summary of this text. 
    Make sure the summary is accurate and helpful.
    Text: {text}
  """

  map_prompt_template = ChatPromptTemplate.from_template(
    map_prompt
  )

  reduce_prompt = """
    Please make an accurate final concise summary of all this text.
    The summary should not be more than 5 lines or 80-100 words
    Make sure you generate the most accurate and helpful summary which is useful to the user.
    Text: {text}
  """

  reduce_prompt_template = ChatPromptTemplate.from_template(
    reduce_prompt
  )

  summarization_chain = load_summarize_chain(
    llm = llm,
    chain_type='map_reduce',
    map_prompt=map_prompt_template,
    combine_prompt=reduce_prompt_template,
    verbose=False
  )

  result = summarization_chain.invoke(final_text_docs)
  summary = result['output_text']
  
  return summary # Return the final summary generated by LLM


if __name__ == "__main__":
  print(transcript_summarizer('input-transcripts/transcript.txt'))